### ISSUE TITLE
Includes not working

### ISSUE THREAD

**Issue by Rincewind3d** [exaptis/asciidoctor-loader#6]
Please add an example how includes should work.

**Webpack 3.4.0 config**
```
    rules: [
        {
            test: /\.adoc/,
            use: [
                {
                    loader: "html-loader"
                },
                {
                    loader: "asciidoctor-loader",
                    options: {
                        attributes: 'showtitle'
                    }
                }
            ]

        }
    ]
```

**File: src/adoc/foobar.adoc**
```
= Hello,  World

include test

include::foo.adoc[]
```

**File: src/adoc/foo.adoc**
```
content of foo
```

**File: src/js/app.js**
 ```
import content from '../adoc/foobar.adoc';
document.querySelector('body').innerHTML = content;
```

**Error:**
```
    ERROR in ./src/adoc/foobar.adoc
    Module build failed: Error: ENOENT: no such file or directory, open 'foo.adoc'
        at Object.fs.openSync (fs.js:652:18)
        at $File.ːinitialize [as $initialize] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:20294:40)
        at singleton_class_alloc.TMP_4 [as $new] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/opal-runtime/src/opal.js:3139:23)
        at $PreprocessorReader.ːopen [as $open] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:20254:45)
        at $PreprocessorReader.ːpreprocess_include [as $preprocess_include] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31684:86)
        at $PreprocessorReader.ːprocess_line [as $process_line] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31380:36)
        at $PreprocessorReader.ːpeek_line [as $peek_line] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:30986:41)
        at $PreprocessorReader.ːpeek_line [as $peek_line] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31411:129)
        at $PreprocessorReader.ːskip_blank_lines [as $skip_blank_lines] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:31099:41)
        at singleton_class_alloc.ːnext_section [as $next_section] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:28673:16)
        at singleton_class_alloc.ːnext_section [as $next_section] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:28633:23)
        at singleton_class_alloc.ːparse [as $parse] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:28479:21)
        at $Document.ːparse [as $parse] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:27419:32)
        at module_constructor.ːload [as $load] (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:33226:65)
        at module_constructor.ːconvert (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:33306:20)
        at module_constructor.Opal.Asciidoctor.$$class.$$proto.convert (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/node_modules/asciidoctor.js/dist/asciidoctor.js:33455:21)
        at Object.module.exports (/Users/pizza/asciidoc-test/node_modules/asciidoctor-loader/index.js:20:22)
     @ ./src/js/app.js 3:0-43
```

**Comment by Rincewind3d** [comment]
It seems to be a asciidoctor.js issue:
https://github.com/asciidoctor/asciidoctor.js/issues/381

**Comment by Rincewind3d** [comment]
Fixed it in loader, see my pull request:
https://github.com/exaptis/asciidoctor-loader/pull/5
